WINDOW_WIDTH = 600
WINDOW_HEIGHT = WINDOW_WIDTH
FPS = 60

BG_COLOR = (50, 50, 50)

TRIANGLE_SIDE = WINDOW_WIDTH * .8
TRIANGLE_COLOR = (0, 0, 0)

SQUARE_SIDE = TRIANGLE_SIDE / 20
SQUARE_COLOR = (255, 0, 0)
SQUARE_OUTLINE_COLOR = TRIANGLE_COLOR
